# Generated by Django 3.1.5 on 2021-01-30 09:47

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('Leaveapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procurementapplication',
            options={'permissions': (('can_cancel', 'Can cancel'), ('can_approve_reject', 'can approve and reject'))},
        ),
        migrations.AlterField(
            model_name='procurementapplication',
            name='status',
            field=django_fsm.FSMIntegerField(default=1, protected=True),
        ),
    ]
