# Generated by Django 3.1.5 on 2021-01-30 09:52

import Leaveapp.models
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('Leaveapp', '0002_auto_20210130_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementapplication',
            name='status',
            field=django_fsm.FSMIntegerField(default=Leaveapp.models.StateEnum['CREATED'], protected=True),
        ),
    ]
