# Generated by Django 3.1.5 on 2021-01-30 10:04

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('Leaveapp', '0003_auto_20210130_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementapplication',
            name='status',
            field=django_fsm.FSMField(choices=[('CANCELLED', 'CANCELLED'), ('CREATED', 'CREATED'), ('REJECTED', 'REJECTED'), ('DIRS_APPROVED', 'DIRS_APPROVED'), ('PD_APPROVED', 'PD_APPROVED')], default=('CANCELLED', 'CANCELLED'), max_length=50),
        ),
    ]
