# Generated by Django 3.1.5 on 2021-02-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaveapp', '0007_auto_20210130_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procurementapplication',
            options={'permissions': (('can_cancel', 'Can cancel'), ('can_check', 'Can check'), ('can_approve_reject', 'can approve and reject'))},
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
