# Generated by Django 3.1.5 on 2021-02-13 04:47

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('Leaveapp', '0008_auto_20210213_0428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procurementapplication',
            options={'permissions': (('can_cancel', 'Can cancel'), ('can_check', 'Can check and return'), ('can_approve', 'can approve and reject'))},
        ),
        migrations.AlterField(
            model_name='procurementapplication',
            name='status',
            field=django_fsm.FSMField(choices=[('CANCELLED', 'CANCELLED'), ('CREATED', 'CREATED'), ('CHECKED', 'CHECKED'), ('RETURNED', 'RETURNED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default=('CREATED', 'CREATED'), max_length=50),
        ),
    ]
