# Generated by Django 3.1.5 on 2021-02-13 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leaveapp', '0009_auto_20210213_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisioncomment_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisioncomment_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('related_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisioncomment_application', to='Leaveapp.procurementapplication')),
            ],
        ),
    ]
