# Generated by Django 3.1.5 on 2021-02-13 14:19

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('Leaveapp', '0010_revisioncomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementapplication',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'cancelled'), (1, 'created'), (2, 'fulfilled'), (3, 'cancelled'), (4, 'returned'), (5, 'rejected')], default=1, protected=True),
        ),
    ]
