# Generated by Django 3.1.5 on 2021-02-13 15:44

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('Leaveapp', '0011_auto_20210213_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementapplication',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'cancelled'), (1, 'created'), (2, 'revised'), (3, 'checked'), (4, 'returned'), (5, 'approved')], default=1, protected=True),
        ),
    ]
